// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA305A0XbvcMENjWmHhUg-ynopFt2w_s60',
    appId: '1:43088967982:web:e2bb417b553ba7746422bf',
    messagingSenderId: '43088967982',
    projectId: 'aplicacaoflutter-01',
    authDomain: 'aplicacaoflutter-01.firebaseapp.com',
    storageBucket: 'aplicacaoflutter-01.firebasestorage.app',
    measurementId: 'G-WPS9392S5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtni8qA4cz0s_Xcz29C6v8xQ-cmPmT-_o',
    appId: '1:43088967982:android:cdf46f3763048af16422bf',
    messagingSenderId: '43088967982',
    projectId: 'aplicacaoflutter-01',
    storageBucket: 'aplicacaoflutter-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKccgij3FPb1p3ObtYw07GLB1CdO4fHkc',
    appId: '1:43088967982:ios:7e600e0aab80d4da6422bf',
    messagingSenderId: '43088967982',
    projectId: 'aplicacaoflutter-01',
    storageBucket: 'aplicacaoflutter-01.firebasestorage.app',
    androidClientId: '43088967982-16pucil8o3ljkp3h7cnkll498pvsgi5h.apps.googleusercontent.com',
    iosClientId: '43088967982-3ndpuvcif28rk05ifbo4um2dhi7lf0jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKccgij3FPb1p3ObtYw07GLB1CdO4fHkc',
    appId: '1:43088967982:ios:7e600e0aab80d4da6422bf',
    messagingSenderId: '43088967982',
    projectId: 'aplicacaoflutter-01',
    storageBucket: 'aplicacaoflutter-01.firebasestorage.app',
    androidClientId: '43088967982-16pucil8o3ljkp3h7cnkll498pvsgi5h.apps.googleusercontent.com',
    iosClientId: '43088967982-3ndpuvcif28rk05ifbo4um2dhi7lf0jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projetoFlutter01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA305A0XbvcMENjWmHhUg-ynopFt2w_s60',
    appId: '1:43088967982:web:2df9006094b0d4696422bf',
    messagingSenderId: '43088967982',
    projectId: 'aplicacaoflutter-01',
    authDomain: 'aplicacaoflutter-01.firebaseapp.com',
    storageBucket: 'aplicacaoflutter-01.firebasestorage.app',
    measurementId: 'G-0P7BEZP3J5',
  );
}
